version: '3.7'

services: 
  database_ps:
    image: postgres
    container_name: database_ps
    restart: always
    ports: 
      - 5432:5432
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  app:
    build: .
    container_name: demo
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local